// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.26.1";

// src/lib/mcp/tools/get-profile.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.26.1";

// src/i18n/translations/en.ts
var en = {
  dir: "ltr",
  nav: {
    home: "Home",
    procedures: "Procedures",
    expertise: "Expertise",
    about: "About & CV",
    research: "Research",
    resilience: "Resilience",
    press: "Press",
    contact: "Contact"
  },
  hero: {
    slogan1: "Saving Lives",
    slogan2: "Every Heartbeat Counts",
    name: "Prof. Israel M. Barbash, MD",
    title: "Director of Cath Lab Services",
    institution: "Leviev Heart Center  \xB7  Sheba Medical Center",
    tagline: "Leading the most demanding unit in one of the highest-ranked hospitals in the world",
    stats: {
      publications: "Publications",
      citations: "Citations",
      annualProcedures: "Annual Team Procedures",
      yearsExperience: "Years Experience",
      worldBest: "World's Best Hospital",
      newsweek: "Newsweek 2026"
    }
  },
  procedures: {
    sectionLabel: "Catheterization Laboratories",
    heading: "Life-Saving Procedures Annually",
    subheading: "Led by Prof. Barbash \u2014 5 State-of-the-Art Catheterization Laboratories \u2014 The Largest in Israel",
    categories: {
      diagnostic: {
        title: "Diagnostic",
        items: ["Coronary Angiography", "Right & Left Heart Catheterization", "FFR/iFR", "IVUS", "OCT"]
      },
      coronary: {
        title: "Coronary Interventions (PCI)",
        items: ["PCI with Drug-Eluting Stents", "CTO PCI", "Left Main PCI", "Bifurcation Stenting", "Rotational Atherectomy", "Intravascular Lithotripsy", "Balloon Angioplasty", "Drug-Coated Balloons", "Thrombectomy"]
      },
      structural: {
        title: "Structural Heart",
        items: ["TAVR/TAVI", "Transcaval Access", "Balloon Aortic Valvuloplasty", "MitraClip/TEER", "Tricuspid Interventions", "ASD/PFO Closure", "Left Atrial Appendage Closure (Watchman)", "Alcohol Septal Ablation"]
      },
      hemodynamic: {
        title: "Hemodynamic Support",
        items: ["IABP", "Impella", "ECMO (100+/year)", "Pericardiocentesis", "Endomyocardial Biopsy"]
      },
      peripheral: {
        title: "Peripheral Vascular",
        items: ["Peripheral Angiography & PTA", "Carotid Stenting", "Renal Artery Intervention"]
      }
    }
  },
  expertise: {
    sectionLabel: "Specializations",
    heading: "Areas of",
    headingAccent: "Expertise",
    cards: [
      {
        title: "TAVR / TAVI",
        desc: "Transcatheter Aortic Valve Replacement \u2014 pioneering minimally invasive therapy for severe aortic stenosis. Contributing to Israel's National TAVR Registry: 6,191+ patients, 5-year survival 70%, 8-year survival improved from 39% to 71%."
      },
      {
        title: "Structural Heart Interventions",
        desc: "Advanced catheter-based valve repair and replacement: MitraClip/TEER, tricuspid interventions, ASD/PFO closure, left atrial appendage closure. Pioneer of transcaval access technique developed at NIH."
      },
      {
        title: "Complex Coronary Interventions",
        desc: "Expert in chronic total occlusion (CTO) PCI, left main interventions, bifurcation stenting, rotational atherectomy, intravascular lithotripsy, and high-risk PCI with mechanical support."
      },
      {
        title: "Cardiovascular Big Data & AI",
        desc: "Leading SHEBAHEART \u2014 Israel's largest cardiovascular big data registry (115,000+ admissions/year). Integrating AI and Large Language Models into clinical decision support for acute coronary syndrome."
      }
    ]
  },
  about: {
    sectionLabel: "Biography",
    heading: "A Career Defined by",
    headingAccent: "Excellence",
    photoAlt: "Professor Israel M. Barbash, MD \u2014 Interventional Cardiologist",
    bio: "Professor Barbash is among the world's leading experts in transcatheter aortic valve replacement (TAVR) and structural heart interventions. With training at the National Institutes of Health and Cleveland Clinic, and over two decades of clinical and research excellence, he leads one of the largest catheterization laboratories in Israel \u2014 his team performs approximately 7,000 procedures annually at Sheba Medical Center, ranked #7 in the world by Newsweek.",
    cvLabel: "Curriculum Vitae",
    cvHeading: "Full",
    cvAccent: "CV",
    downloadCV: "Download Full CV",
    milestones: [
      { year: "1973", title: "Born", desc: "August 11, Israel" },
      { year: "1991\u201394", title: "Air Force Service", desc: "Israel Defense Forces" },
      { year: "1994\u201302", title: "MD, Medical Degree", desc: "Ben-Gurion University of the Negev" },
      { year: "2000\u201301", title: "Research Fellowship", desc: "Neufeld Cardiac Research Institute" },
      { year: "2003\u201309", title: "Residency", desc: "Internal Medicine & Cardiology (6-year program), Sheba Medical Center. Board Certified Summa Cum Laude." },
      { year: "2009", title: "Cardiac CT Training", desc: "Johns Hopkins University" },
      { year: "2009\u201311", title: "NIH Fellowship", desc: "NHLBI, National Institutes of Health, Bethesda, MD \u2014 Cardiovascular Intervention Program" },
      { year: "2011\u201313", title: "Interventional Fellowship", desc: "MedStar\u2013Cleveland Clinic, Georgetown University, Washington DC. ECFMG Certified (USMLE Steps 1, 2, 3)." },
      { year: "Present", title: "Director, Cath Lab Services", desc: "Leviev Heart Center, Sheba Medical Center" },
      { year: "Present", title: "Associate Professor", desc: "Sackler Faculty of Medicine, Tel Aviv University" },
      { year: "Present", title: "Chair", desc: "Working Group on Interventional Cardiology, Israel Heart Society" }
    ],
    cvSections: [
      {
        title: "Patents",
        content: [
          "2008 \u2014 Cardiac stem cell isolation methods (PCT/IL2008/000026)",
          "2010 \u2014 Closure device for cardiac surgery (61/382,931)"
        ]
      },
      {
        title: "Awards & Honors",
        content: [
          "Klapholtz Award for Cardiovascular Research, Tel Aviv University (2001)",
          "Neufeld Prize, Israel Heart Society (2004)",
          "B. de Rothschild Fund, Israel Academy of Sciences \u2014 National Clinician-Investigator Program (2004) \u2014 only 3\u20134 selected per year",
          "Talpiot Medical Leadership Program, Sheba Medical Center (2006)",
          "AHA New Investigator Travel Award (2007)",
          "AiroMedical Rating: 9.80 / 10"
        ]
      },
      {
        title: "Research Grants (Selected)",
        content: [
          "European Commission 7th Framework Programme \u2014 \u20AC280,000 (\u20AC2.7M consortium) \u2014 cardiac stem cell therapy",
          "Seymour Fefer Cardiovascular Research Grants \u2014 nanoparticle theranostics, cardiac MRI for TAVR"
        ]
      },
      {
        title: "Professional Memberships",
        content: [
          "Israel Society of Cardiology (1998\u2013present)",
          "European Society of Cardiology (2003\u2013present)",
          "American Heart Association",
          "American College of Cardiology"
        ]
      },
      {
        title: "Journal Reviewer",
        content: [
          "American Journal of Cardiology",
          "European Heart Journal",
          "Cardiovascular Revascularization Medicine",
          "EuroIntervention",
          "Catheterization and Cardiovascular Interventions"
        ]
      },
      {
        title: "Publications Summary",
        content: [
          "284 peer-reviewed publications",
          "9,087+ citations (ResearchGate) / ~7,400+ (Google Scholar)",
          "Top journals: Circulation (IF 15.2), JACC (IF 14.1), European Heart Journal (IF 14.1)",
          "3 book chapters, 80+ conference abstracts"
        ]
      }
    ]
  },
  research: {
    sectionLabel: "Impact",
    heading: "Research &",
    headingAccent: "Publications",
    pubLabel: "Peer-Reviewed Publications",
    photoAlt: "Prof. Israel M. Barbash \u2014 Researcher and Clinician",
    stats: [
      ["9,000+", "Citations"],
      ["245", "Research Works"],
      ["NIH", "Fellowship Alumni"]
    ],
    highlights: [
      { title: "National TAVR Registry", detail: "6,191 patients across 4 centers | 5-year survival: 70% | 10-year survival: 42% | 8-year survival leap: 39% \u2192 71%" },
      { title: "Transcaval Access Innovation", detail: "Developed at NIH. Hospital stay: 6.3 vs 14.4 days | Kidney injury: 5% vs 12%" },
      { title: "AI & MicroRNA Biomarkers", detail: "Prognostic miR-21, miR-1, miR-210 post-TAVR | LLMs achieving 86% accuracy in ACS decision support" }
    ],
    qualityHeading: "Quality Metrics",
    qualityAccent: "Over the Years",
    timeline: [
      { year: "2008", event: "First TAVR at Sheba" },
      { year: "2010\u201315", event: "Early era \u2014 building registry, refining techniques" },
      { year: "2016\u201323", event: "Modern era \u2014 dramatic improvement in outcomes" },
      { year: "Metrics", event: "Pacemaker rates ~18% \xB7 Vascular complications significantly decreased \xB7 Device success 95%" },
      { year: "2023", event: "766 open-heart procedures performed \u2014 increase despite war conditions" }
    ]
  },
  resilience: {
    heading: "When Rockets Fell,",
    headingAccent: "The Cath Lab Never Closed",
    body: "On October 7, 2023, Israel faced its most devastating attack. As rockets flew overhead and sirens wailed, Sheba Medical Center \u2014 the nation's largest hospital \u2014 became the frontline of healing. Prof. Barbash and his team in the catheterization laboratories never stopped. While 50% of cardiac surgeons were recruited to military service, Sheba's cardiac department performed MORE procedures than the previous year \u2014 766 open-heart operations in 2023, compared to 732 in 2022. The cath lab continued its mission: ~7,000 procedures, saving lives every single day.",
    stats: [
      { label: "Wounded Treated After Oct 7" },
      { label: "Open-Heart Procedures in 2023" },
      { label: "Increase in Heart Transplants" },
      { label: "Surgeons Called to Duty" }
    ],
    continuous: "Continuous Operations",
    countries: "Countries Served",
    closing: "This is the unit Prof. Barbash leads \u2014 the most demanding department in one of the world's highest-ranked hospitals. A unit that didn't just survive wartime \u2014 it thrived. Treating soldiers and civilians, Jews and Arabs, Israelis and Palestinians \u2014 because in the cath lab, the only thing that matters is the heartbeat on the monitor."
  },
  press: {
    sectionLabel: "Media",
    heading: "Press &",
    headingAccent: "Publications",
    categories: ["All", "Interviews", "Publications", "Conferences", "News"],
    readMore: "Read More",
    items: [
      { title: "ICI Meeting \u2014 Invited Speaker", source: "ICI Meeting", category: "Conferences", desc: "Innovations in Cardiovascular Interventions, Tel Aviv", link: "https://icimed.org/staff/israel-barbash/" },
      { title: "ESC 365 \u2014 Contributor", source: "European Society of Cardiology", category: "Publications", desc: "ESC knowledge hub contributor", link: "https://esc365.escardio.org" },
      { title: "CRT 2013 & 2015 \u2014 Invited Lectures", source: "CRT", category: "Conferences", desc: "Cardiovascular Research Technologies, Washington DC" },
      { title: "EAPCI Core Curriculum", source: "EAPCI", category: "Publications", desc: "Committee for Education and Training (2020)" },
      { title: "Cardiac Surgery During Wartime", source: "PMC / NIH", category: "Publications", desc: "Surprising increase in procedures despite 50% surgeon mobilization", link: "https://pubmed.ncbi.nlm.nih.gov" },
      { title: "Sheba Underground Hospital", source: "The Media Line", category: "News", desc: "Safe haven in wartime for critically ill", link: "https://themedialine.org" },
      { title: "Sheba Treating Victims", source: "CNN", category: "News", desc: "Sheba treating victims with severe injuries" },
      { title: "Sheba #7 in World", source: "Newsweek 2026", category: "News", desc: "World's Best Hospitals ranking", link: "https://newsweek.com" },
      { title: "Sanofi Center of Excellence", source: "Sanofi", category: "News", desc: "Leviev Heart Center Clinical Research Unit designation" },
      { title: "AsiaIntervention Publication", source: "AsiaIntervention", category: "Publications", desc: "EAPCI curriculum publication" }
    ]
  },
  institutions: {
    sectionLabel: "Institutional Excellence",
    items: [
      "Sheba Medical Center \u2014 #7 World's Best Hospital",
      "NIH / NHLBI",
      "Cleveland Clinic",
      "Johns Hopkins University",
      "Tel Aviv University \u2014 Sackler Faculty of Medicine",
      "EAPCI / ESC",
      "Newsweek Top 10",
      "Israel Heart Society",
      "Sanofi Center of Excellence",
      "Talpiot Medical Leadership Program"
    ]
  },
  philosophy: {
    quote: '"The numbers tell one story. But behind every statistic is a person \u2014 a father, a mother, a grandparent \u2014 who was given more time. That is the only metric that truly matters."',
    source: "\u2014 Prof. Israel M. Barbash",
    note: "Note: This is an aspirational quote for the website. The actual quote should be confirmed with Prof. Barbash."
  },
  contact: {
    sectionLabel: "Get in Touch",
    heading: "Contact",
    thankYou: "Thank you",
    messageReceived: "Your message has been received.",
    placeholders: {
      name: "Full Name",
      email: "Email Address",
      phone: "Phone (optional)",
      institution: "Institution (optional)",
      message: "Your Message"
    },
    sendButton: "Send Message",
    heartCenter: "Leviev Heart Center",
    shebaCenter: "Sheba Medical Center",
    location: "Ramat Gan, Israel",
    languages: "Languages: Hebrew, English",
    academicProfiles: "Academic Profiles"
  },
  footer: {
    copyright: "\xA9 2026 Prof. Israel M. Barbash, MD \u2014 All Rights Reserved",
    hebrewNote: "\u05D0\u05EA\u05E8 \u05D6\u05D4 \u05D6\u05DE\u05D9\u05DF \u05D2\u05DD \u05D1\u05E2\u05D1\u05E8\u05D9\u05EA"
  }
};

// src/lib/mcp/tools/get-profile.ts
var get_profile_default = defineTool({
  name: "get_profile",
  title: "Get profile",
  description: "Get the public profile of Prof. Israel M. Barbash, MD: name, title, institution, biography, career milestones and philosophy.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => {
    const profile = {
      name: en.hero.name,
      title: en.hero.title,
      institution: en.hero.institution,
      tagline: en.hero.tagline,
      biography: en.about.bio,
      milestones: en.about.milestones,
      institutions: en.institutions.items,
      philosophy: en.philosophy.quote
    };
    return {
      content: [{ type: "text", text: JSON.stringify(profile, null, 2) }],
      structuredContent: profile
    };
  }
});

// src/lib/mcp/tools/list-procedures.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z } from "npm:zod@^4.4.3";
var categories = en.procedures.categories;
var list_procedures_default = defineTool2({
  name: "list_procedures",
  title: "List procedures",
  description: "List the cardiac catheterization procedures performed by Prof. Barbash's team, optionally filtered to a single category.",
  inputSchema: {
    category: z.enum(["diagnostic", "coronary", "structural", "hemodynamic", "peripheral"]).optional().describe("Optional category filter. Omit to return all categories.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ category }) => {
    const keys = category ? [category] : Object.keys(categories);
    const result = {
      heading: en.procedures.subheading,
      categories: keys.map((key) => ({
        key,
        title: categories[key].title,
        procedures: categories[key].items
      }))
    };
    return {
      content: [{ type: "text", text: JSON.stringify(result, null, 2) }],
      structuredContent: result
    };
  }
});

// src/lib/mcp/tools/get-expertise.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.26.1";
var get_expertise_default = defineTool3({
  name: "get_expertise",
  title: "Get areas of expertise",
  description: "Get Prof. Barbash's clinical areas of expertise (TAVR/TAVI, structural heart, complex coronary interventions, cardiovascular big data & AI) with descriptions.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => {
    const result = { areas: en.expertise.cards };
    return {
      content: [{ type: "text", text: JSON.stringify(result, null, 2) }],
      structuredContent: result
    };
  }
});

// src/lib/mcp/tools/get-cv.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z2 } from "npm:zod@^4.4.3";
var get_cv_default = defineTool4({
  name: "get_cv",
  title: "Get CV",
  description: "Get Prof. Barbash's curriculum vitae sections: patents, awards & honors, research grants, professional memberships, journal reviewer roles and publications summary.",
  inputSchema: {
    section: z2.string().optional().describe("Optional case-insensitive section title filter, e.g. 'Awards' or 'Patents'.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ section }) => {
    const query = section?.trim().toLowerCase();
    const sections = query ? en.about.cvSections.filter((s) => s.title.toLowerCase().includes(query)) : en.about.cvSections;
    const result = { milestones: en.about.milestones, sections };
    return {
      content: [{ type: "text", text: JSON.stringify(result, null, 2) }],
      structuredContent: result
    };
  }
});

// src/lib/mcp/tools/get-research.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.26.1";
var get_research_default = defineTool5({
  name: "get_research",
  title: "Get research and outcomes",
  description: "Get research impact for Prof. Barbash: citation and publication stats, research highlights (National TAVR Registry, transcaval access, AI/microRNA biomarkers) and quality-metric timeline.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => {
    const result = {
      stats: en.research.stats.map(([value, label]) => ({ value, label })),
      highlights: en.research.highlights,
      qualityTimeline: en.research.timeline,
      wartimeResilience: {
        summary: en.resilience.body,
        closing: en.resilience.closing
      }
    };
    return {
      content: [{ type: "text", text: JSON.stringify(result, null, 2) }],
      structuredContent: result
    };
  }
});

// src/lib/mcp/tools/list-press.ts
import { defineTool as defineTool6 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z3 } from "npm:zod@^4.4.3";
var list_press_default = defineTool6({
  name: "list_press",
  title: "List press and media",
  description: "List press mentions, interviews, conference lectures and publications featuring Prof. Barbash, optionally filtered by category.",
  inputSchema: {
    category: z3.enum(["Interviews", "Publications", "Conferences", "News"]).optional().describe("Optional category filter. Omit to return all items.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ category }) => {
    const items = category ? en.press.items.filter((item) => item.category === category) : en.press.items;
    const result = { count: items.length, items };
    return {
      content: [{ type: "text", text: JSON.stringify(result, null, 2) }],
      structuredContent: result
    };
  }
});

// src/lib/mcp/tools/get-contact.ts
import { defineTool as defineTool7 } from "npm:@lovable.dev/mcp-js@0.26.1";
var get_contact_default = defineTool7({
  name: "get_contact",
  title: "Get contact information",
  description: "Get public contact details for Prof. Barbash's practice: heart center, medical center, location and languages spoken.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => {
    const result = {
      heartCenter: en.contact.heartCenter,
      medicalCenter: en.contact.shebaCenter,
      location: en.contact.location,
      languages: en.contact.languages,
      website: "https://barbash-legacy-site.lovable.app",
      note: "Use the contact form on the website to send a message."
    };
    return {
      content: [{ type: "text", text: JSON.stringify(result, null, 2) }],
      structuredContent: result
    };
  }
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "barbash-legacy",
  title: "Barbash Legacy",
  version: "0.1.0",
  instructions: "Public tools for the professional site of Prof. Israel M. Barbash, MD, Director of Cath Lab Services at the Leviev Heart Center, Sheba Medical Center. Use `get_profile` for biography and career, `list_procedures` for the catheterization procedures offered, `get_expertise` for clinical specializations, `get_cv` for awards, patents, grants and publication stats, `get_research` for research impact and outcomes, `list_press` for media and conference appearances, and `get_contact` for practice location and contact details. All data is public website content.",
  tools: [
    get_profile_default,
    list_procedures_default,
    get_expertise_default,
    get_cv_default,
    get_research_default,
    list_press_default,
    get_contact_default
  ]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.26.1/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
